version: 2.1

jobs:
  build_model:
    machine:
      resource_class: gpu.nvidia.small.gen2
      image: linux-cuda-11:default
    steps:
      - checkout
      - run:
          name: Check GPU status
          command: nvidia-smi
      - run:
          name: Set up a dataset from Roboflow
          command: |
            cd /opt/circleci
            mkdir datasets; cd datasets
            curl -L "https://public.roboflow.com/ds/ogCNcy2gya?key=$ROBOFLOW_KEY" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
      - run:
          name: Build a model
          command: |
            pip3 install ultralytics
            cd /opt/circleci/datasets
            yolo task=detect mode=train model=yolov8n.pt data=data.yaml epochs=100 imgsz=640 batch=64
      - store_artifacts:
          path: /opt/circleci/.pyenv/runs/detect/train
          destination: train
      - run:
          name: Set up Hugging Face CLI
          command:  pip3 install -U "huggingface_hub[cli]"
      - run:
          name: Upload the model to Hugging Face
          command: |
            huggingface-cli login --token $HUGGINGFACE_TOKEN
            huggingface-cli upload mfunaki/cci-gpu-yolov8-maskdetection \
              /opt/circleci/.pyenv/runs/detect/train/weights/best.pt \
              mask_best.pt

workflows:
  mask_detection_training:
    jobs:
      - build_model
